openapi: 3.0.3
info:
  title: Patient Workflow System API
  version: 1.1.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /auth/register:
    post: { summary: Register a user, responses: { "201": { description: Created } } }
  /auth/login:
    post: { summary: Login and set httpOnly cookies, responses: { "200": { description: OK } } }
  /auth/logout:
    post: { summary: Logout and clear cookies, responses: { "204": { description: No Content } } }
  /doctors:
    get: { summary: List doctors, responses: { "200": { description: OK } } }
    post: { summary: Create doctor (admin/superadmin), responses: { "201": { description: Created } } }
  /doctors/{id}:
    get: { summary: Get doctor by id, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "200": { description: OK }, "404": { description: Not Found } } }
    put: { summary: Update doctor, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "200": { description: OK }, "403": { description: Forbidden }, "404": { description: Not Found } } }
    delete: { summary: Delete doctor, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "204": { description: No Content }, "404": { description: Not Found } } }
  /schedules:
    get: { summary: List schedules, responses: { "200": { description: OK } } }
    post: { summary: Create schedule, responses: { "201": { description: Created } } }
  /schedules/{id}:
    get: { summary: Get schedule, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "200": { description: OK }, "404": { description: Not Found } } }
    put: { summary: Update schedule, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "200": { description: OK } } }
    delete: { summary: Delete schedule, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "204": { description: No Content } } }
  /appointments:
    get: { summary: List appointments, responses: { "200": { description: OK } } }
    post: { summary: Create appointment, responses: { "201": { description: Created } } }
  /appointments/{id}/status:
    put: { summary: Update appointment status, parameters: [{ in: path, name: id, required: true, schema: { type: string } }], responses: { "200": { description: OK } } }
  /medical-records/{appointmentId}:
    get: { summary: Get medical record by appointment, parameters: [{ in: path, name: appointmentId, required: true, schema: { type: string } }], responses: { "200": { description: OK }, "404": { description: Not Found } } }
  /medical-records:
    post: { summary: Upsert medical record, responses: { "201": { description: Created } } }
  /analytics/visits-by-day:
    get: { summary: Visits by day (admin), responses: { "200": { description: OK } } }
  /analytics/visits-by-doctor:
    get: { summary: Visits by doctor (admin), responses: { "200": { description: OK } } }
  /analytics/visits-by-specialty:
    get: { summary: Visits by specialty (admin), responses: { "200": { description: OK } } }
